env:
  browser: true
  es2020: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: tsconfig.json

plugins:
  - "@typescript-eslint"

rules:
  indent:
    - error
    - 2

  linebreak-style:
    - error
    - windows

  quotes:
    - error
    - single

  semi:
    - error
    - always

  comma-dangle:
    - error
    - always-multiline
